import { Button } from "@/components/ui/button";
import { Link } from "lucide-react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={inter.className}>
        <header className="border-b conitems-center h-16 flex px-6">
          <div className="container flex">
            <Button
              className="items-center font-bold text-lg"
              asChild
              variant={"ghost"}>
              <Link href="/">高橋商店</Link>
            </Button>
          </div>
        </header>
        <main>{children}</main>
        <footer className="border-t items-center h-16 flex px-6">
          <div className="container ">
            <p>© 2024 高橋商店</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
